// Generated by https://quicktype.io

export interface HomeModel {
    status:       string;
    totalResults: number;
    articles:     Article[];
}

export interface Article {
    source:      Source;
    author:      null;
    title:       string;
    description: string;
    url:         string;
    urlToImage:  string;
    publishedAt: string;
    content:     null | string;
}

export interface Source {
    id:   string;
    name: string;
}
